Traceback (most recent call last):
  File "/home/dell/.local/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
with imageio.get_writer('mygif.gif', mode='I') as writer:
    for filename in os.listdir('gifplot'):
        image = imageio.imread('gifplot/{}'.format(filename))
        writer.append_data(image)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-30-1b56c7938866>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mwith[0m [0mimageio[0m[0;34m.[0m[0mget_writer[0m[0;34m([0m[0;34m'mygif.gif'[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0;34m'I'[0m[0;34m)[0m [0;32mas[0m [0mwriter[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m     [0;32mfor[0m [0mfilename[0m [0;32min[0m [0mos[0m[0;34m.[0m[0mlistdir[0m[0;34m([0m[0;34m'gifplot'[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m         [0mimage[0m [0;34m=[0m [0mimageio[0m[0;34m.[0m[0mimread[0m[0;34m([0m[0;34m'gifplot/{}'[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mfilename[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m         [0mwriter[0m[0;34m.[0m[0mappend_data[0m[0;34m([0m[0mimage[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'os' is not defined
NameError: name 'os' is not defined

