Traceback (most recent call last):
  File "/home/dell/.local/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# ƒê·ªãnh d·∫°ng npy
np.save('numpy_save/A', A)
# ƒê·ªãnh d·∫°ng txt
np.savetxt('numpy_save/A.txt', A)
# List c√°c file
!ls -a numpy_save
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-9-8a55139de344>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# ƒê·ªãnh d·∫°ng npy[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mnp[0m[0;34m.[0m[0msave[0m[0;34m([0m[0;34m'numpy_save/A'[0m[0;34m,[0m [0mA[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;31m# ƒê·ªãnh d·∫°ng txt[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mnp[0m[0;34m.[0m[0msavetxt[0m[0;34m([0m[0;34m'numpy_save/A.txt'[0m[0;34m,[0m [0mA[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;31m# List c√°c file[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m<__array_function__ internals>[0m in [0;36msave[0;34m(*args, **kwargs)[0m

[0;32m~/.local/lib/python3.6/site-packages/numpy/lib/npyio.py[0m in [0;36msave[0;34m(file, arr, allow_pickle, fix_imports)[0m
[1;32m    522[0m         [0;32mif[0m [0;32mnot[0m [0mfile[0m[0;34m.[0m[0mendswith[0m[0;34m([0m[0;34m'.npy'[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    523[0m             [0mfile[0m [0;34m=[0m [0mfile[0m [0;34m+[0m [0;34m'.npy'[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 524[0;31m         [0mfile_ctx[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0mfile[0m[0;34m,[0m [0;34m"wb"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    525[0m [0;34m[0m[0m
[1;32m    526[0m     [0;32mwith[0m [0mfile_ctx[0m [0;32mas[0m [0mfid[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'numpy_save/A.npy'
FileNotFoundError: [Errno 2] No such file or directory: 'numpy_save/A.npy'

