Traceback (most recent call last):
  File "/home/dell/.local/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/dell/miniconda3/envs/deepai-book/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/dell/.local/lib/python3.6/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pprint
from cvxopt import matrix, solvers
c = matrix([50., 150., 120., 40.])

# moi dong cua matrix la 1 list va list nay phai la 1 vec to cot 
G = matrix([[1., 0., -1., 0., 0., 0.],
            [1., 0., 0., -1., 0., 0.],
            [0., 1., 0., 0., -1., 0.],
            [0., 1., 0., 0., 0., -1.]])

h = matrix([1000., 3000., 0., 0., 0., 0.])

A = matrix([[1., 0.],
            [0., 1.],
            [1., 0.],
            [0., 1.]])

b = matrix([1800., 2000.])

solvers.options['show_progress'] = True
sol = solvers.lp(c, G, h, A, b)

print('Solution"')
print(sol['x'])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-e52b5a534919>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mpprint[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0;32mfrom[0m [0mcvxopt[0m [0;32mimport[0m [0mmatrix[0m[0;34m,[0m [0msolvers[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mc[0m [0;34m=[0m [0mmatrix[0m[0;34m([0m[0;34m[[0m[0;36m50.[0m[0;34m,[0m [0;36m150.[0m[0;34m,[0m [0;36m120.[0m[0;34m,[0m [0;36m40.[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0;31m# moi dong cua matrix la 1 list va list nay phai la 1 vec to cot[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'cvxopt'
ModuleNotFoundError: No module named 'cvxopt'

